### PR TITLE
Add functionality to delete a word in insert mode with Control-W.

### PR DESCRIPTION
**Pull request by gregmojonnier**

### CODE REVIEW

**Comment by TheTomster** [comment]
Hey Greg, I'm not sure if I messed something up while reindenting your change or with some other recent change to my code, but this wasn't working for me.  This is what happened after I hit insert, targeted the middle of "copyright" in the LICENSE file, and hit C-w:

```
The above foo    ight notice and this permission
```

So it deleted everything to the left of the cursor, but then things ended up in a kind of weird state.

Also when you do another try, can you indent with tabs? :astonished:

**Comment by gregmojonnier** [comment]
Ah my fault, for some reason I was thinking that this was just supposed to delete a word most recently typed, so essentially just what was to the left of the cursor. I'll modify it to delete the entire word that the cursor is on and repost. And sure, haha sorry about that.

**Comment by TheTomster** [comment]
I think deleting just to the left of the cursor is fine, it's just that 
it put in a bunch of extra spaces somehow. And at the tail end of a word 
I think it was deleting just one letter to the right or something. 
Probably just an off-by-one somewhere now that I think about it haha.

Basically just try C-w in bash and emulate what that does in all these edge cases haha.

**Comment by gregmojonnier** [comment]
Hmmm okay gotcha, haha alright guess I shouldn't be coding so late at night :P I'll see if I can find/fix the issue and will repost in a bit.

**Pull request merged**
